class CreateCountries < ActiveRecord::Migration
  def self.up
    create_table :countries do |t|
      t.string :name
      t.string :abbreviation
      t.timestamps
    end
    
   
    Country.create :name => 'Afghanistan', :abbreviation => 'AF'
    Country.create :name => 'Aland Islands', :abbreviation => 'AX'
    Country.create :name => 'Albania', :abbreviation => 'AL'
    Country.create :name => 'Algeria', :abbreviation => 'DZ'
    Country.create :name => 'American Samoa', :abbreviation => 'AS'
    Country.create :name => 'Andorra', :abbreviation => 'AD'
    Country.create :name => 'Angola', :abbreviation => 'AO'
    Country.create :name => 'Anguilla', :abbreviation => 'AI'
    Country.create :name => 'Antarctica', :abbreviation => 'AQ'
    Country.create :name => 'Antigua and Barbuda', :abbreviation => 'AG'
    Country.create :name => 'Argentina', :abbreviation => 'AR'
    Country.create :name => 'Armenia', :abbreviation => 'AM'
    Country.create :name => 'Aruba', :abbreviation => 'AW'
    Country.create :name => 'Australia', :abbreviation => 'AU'
    Country.create :name => 'Austria', :abbreviation => 'AT'
    Country.create :name => 'Azerbaijan', :abbreviation => 'AZ'
    Country.create :name => 'Bahamas', :abbreviation => 'BS'
    Country.create :name => 'Bahrain', :abbreviation => 'BH'
    Country.create :name => 'Bangladesh', :abbreviation => 'BD'
    Country.create :name => 'Barbados', :abbreviation => 'BB'
    Country.create :name => 'Belarus', :abbreviation => 'BY'
    Country.create :name => 'Belgium', :abbreviation => 'BE'
    Country.create :name => 'Belize', :abbreviation => 'BZ'
    Country.create :name => 'Benin', :abbreviation => 'BJ'
    Country.create :name => 'Bermuda', :abbreviation => 'BM'
    Country.create :name => 'Bhutan', :abbreviation => 'BT'
    Country.create :name => 'Bolivia', :abbreviation => 'BO'
    Country.create :name => 'Bosnia and Herzegovina', :abbreviation => 'BA'
    Country.create :name => 'Botswana', :abbreviation => 'BW'
    Country.create :name => 'Bouvet Island', :abbreviation => 'BV'
    Country.create :name => 'Brazil', :abbreviation => 'BR'
    Country.create :name => 'British Indian Ocean Territory', :abbreviation => 'IO'
    Country.create :name => 'Brunei Darussalam', :abbreviation => 'BN'
    Country.create :name => 'Bulgaria', :abbreviation => 'BG'
    Country.create :name => 'Burkina Faso', :abbreviation => 'BF'
    Country.create :name => 'Burundi', :abbreviation => 'BI'
    Country.create :name => 'Cambodia', :abbreviation => 'KH'
    Country.create :name => 'Cameroon', :abbreviation => 'CM'
    

    Country.create :name => 'Canada', :abbreviation => 'CA'
    Country.create :name => 'Cape Verde', :abbreviation => 'CV'
    Country.create :name => 'Cayman Islands', :abbreviation => 'KY'
    Country.create :name => 'Central African Republic', :abbreviation => 'CF'
    Country.create :name => 'Chad', :abbreviation => 'TD'
    Country.create :name => 'Chile', :abbreviation => 'CL'
    Country.create :name => 'China', :abbreviation => 'CN'
    Country.create :name => 'Christmas Island', :abbreviation => 'CX'
    Country.create :name => 'Cocos (keeling) Islands', :abbreviation => 'CC'
    Country.create :name => 'Colombia', :abbreviation => 'CO'
    Country.create :name => 'Comoros', :abbreviation => 'KM'
    Country.create :name => 'Congo', :abbreviation => 'CG'
    Country.create :name => 'Congo, The Democratic Republic Of The', :abbreviation => 'CD'
    Country.create :name => 'Cook Islands', :abbreviation => 'CK'
    Country.create :name => 'Costa Rica', :abbreviation => 'CR'
    Country.create :name => 'Cote D\'ivoire', :abbreviation => 'CI'
    Country.create :name => 'Croatia', :abbreviation => 'HR'
    Country.create :name => 'Cuba', :abbreviation => 'CU'
    Country.create :name => 'Cyprus', :abbreviation => 'CY'
    Country.create :name => 'Czech Republic', :abbreviation => 'CZ'
    Country.create :name => 'Denmark', :abbreviation => 'DK'
    Country.create :name => 'Djibouti', :abbreviation => 'DJ'
    Country.create :name => 'Dominica', :abbreviation => 'DM'
    Country.create :name => 'Dominican Republic', :abbreviation => 'DO'
    Country.create :name => 'Ecuador', :abbreviation => 'EC'
    Country.create :name => 'Egypt', :abbreviation => 'EG'
    Country.create :name => 'El Salvador', :abbreviation => 'SV'
    Country.create :name => 'Equatorial Guinea', :abbreviation => 'GQ'
    Country.create :name => 'Eritrea', :abbreviation => 'ER'
    Country.create :name => 'Estonia', :abbreviation => 'EE'
    Country.create :name => 'Ethiopia', :abbreviation => 'ET'
    Country.create :name => 'Falkland Islands (malvinas)', :abbreviation => 'FK'
    Country.create :name => 'Faroe Islands', :abbreviation => 'FO'
    Country.create :name => 'Fiji', :abbreviation => 'FJ'
    Country.create :name => 'Finland', :abbreviation => 'FI'
    Country.create :name => 'France', :abbreviation => 'FR'
    Country.create :name => 'French Guiana', :abbreviation => 'GF'
    Country.create :name => 'French Polynesia', :abbreviation => 'PF'
    Country.create :name => 'French Southern Territories', :abbreviation => 'TF'
    Country.create :name => 'Gabon', :abbreviation => 'GA'
    Country.create :name => 'Gambia', :abbreviation => 'GM'
    Country.create :name => 'Georgia', :abbreviation => 'GE'
    Country.create :name => 'Germany', :abbreviation => 'DE'
    Country.create :name => 'Ghana', :abbreviation => 'GH'
    Country.create :name => 'Gibraltar', :abbreviation => 'GI'
    Country.create :name => 'Greece', :abbreviation => 'GR'
    Country.create :name => 'Greenland', :abbreviation => 'GL'
    Country.create :name => 'Grenada', :abbreviation => 'GD'
    Country.create :name => 'Guadeloupe', :abbreviation => 'GP'
    Country.create :name => 'Guam', :abbreviation => 'GU'
    Country.create :name => 'Guatemala', :abbreviation => 'GT'
    Country.create :name => 'Guernsey', :abbreviation => 'GG'
    Country.create :name => 'Guinea', :abbreviation => 'GN'
    Country.create :name => 'Guinea-bissau', :abbreviation => 'GW'
    Country.create :name => 'Guyana', :abbreviation => 'GY'
    Country.create :name => 'Haiti', :abbreviation => 'HT'
    Country.create :name => 'Heard Island and Mcdonald Islands', :abbreviation => 'HM'
    Country.create :name => 'Holy See (vatican City State)', :abbreviation => 'VA'
    Country.create :name => 'Honduras', :abbreviation => 'HN'
    Country.create :name => 'Hong Kong', :abbreviation => 'HK'
    Country.create :name => 'Hungary', :abbreviation => 'HU'
    Country.create :name => 'Iceland', :abbreviation => 'IS'
    Country.create :name => 'India', :abbreviation => 'IN'
    Country.create :name => 'Indonesia', :abbreviation => 'ID'
    Country.create :name => 'Iran, Islamic Republic Of', :abbreviation => 'IR'
    Country.create :name => 'Iraq', :abbreviation => 'IQ'
    Country.create :name => 'Ireland', :abbreviation => 'IE'
    Country.create :name => 'Isle Of Man', :abbreviation => 'IM'
    Country.create :name => 'Israel', :abbreviation => 'IL'
    Country.create :name => 'Italy', :abbreviation => 'IT'
    Country.create :name => 'Jamaica', :abbreviation => 'JM'
    Country.create :name => 'Japan', :abbreviation => 'JP'
    Country.create :name => 'Jersey', :abbreviation => 'JE'
    Country.create :name => 'Jordan', :abbreviation => 'JO'
    Country.create :name => 'Kazakhstan', :abbreviation => 'KZ'
    Country.create :name => 'Kenya', :abbreviation => 'KE'
    Country.create :name => 'Kiribati', :abbreviation => 'KI'
    Country.create :name => 'Korea, Democratic People\'s Republic Of', :abbreviation => 'KP'
    Country.create :name => 'Korea, Republic Of', :abbreviation => 'KR'
    Country.create :name => 'Kuwait', :abbreviation => 'KW'
    Country.create :name => 'Kyrgyzstan', :abbreviation => 'KG'
    Country.create :name => 'Lao People\'s Democratic Republic', :abbreviation => 'LA'
    Country.create :name => 'Latvia', :abbreviation => 'LV'
    Country.create :name => 'Lebanon', :abbreviation => 'LB'
    Country.create :name => 'Lesotho', :abbreviation => 'LS'
    Country.create :name => 'Liberia', :abbreviation => 'LR'
    Country.create :name => 'Libyan Arab Jamahiriya', :abbreviation => 'LY'
    Country.create :name => 'Liechtenstein', :abbreviation => 'LI'
    Country.create :name => 'Lithuania', :abbreviation => 'LT'
    Country.create :name => 'Luxembourg', :abbreviation => 'LU'
    Country.create :name => 'Macao', :abbreviation => 'MO'
    Country.create :name => 'Macedonia, The Former Yugoslav Republic Of', :abbreviation => 'MK'
    Country.create :name => 'Madagascar', :abbreviation => 'MG'
    Country.create :name => 'Malawi', :abbreviation => 'MW'
    Country.create :name => 'Malaysia', :abbreviation => 'MY'
    Country.create :name => 'Maldives', :abbreviation => 'MV'
    Country.create :name => 'Mali', :abbreviation => 'ML'
    Country.create :name => 'Malta', :abbreviation => 'MT'
    Country.create :name => 'Marshall Islands', :abbreviation => 'MH'
    Country.create :name => 'Martinique', :abbreviation => 'MQ'
    Country.create :name => 'Mauritania', :abbreviation => 'MR'
    Country.create :name => 'Mauritius', :abbreviation => 'MU'
    Country.create :name => 'Mayotte', :abbreviation => 'YT'
    Country.create :name => 'Mexico', :abbreviation => 'MX'
    Country.create :name => 'Micronesia, Federated States Of', :abbreviation => 'FM'
    Country.create :name => 'Moldova, Republic Of', :abbreviation => 'MD'
    Country.create :name => 'Monaco', :abbreviation => 'MC'
    Country.create :name => 'Mongolia', :abbreviation => 'MN'
    Country.create :name => 'Montenegro', :abbreviation => 'ME'
    Country.create :name => 'Montserrat', :abbreviation => 'MS'
    Country.create :name => 'Morocco', :abbreviation => 'MA'
    Country.create :name => 'Mozambique', :abbreviation => 'MZ'
    Country.create :name => 'Myanmar', :abbreviation => 'MM'
    Country.create :name => 'Namibia', :abbreviation => 'NA'
    Country.create :name => 'Nauru', :abbreviation => 'NR'
    Country.create :name => 'Nepal', :abbreviation => 'NP'
    Country.create :name => 'Netherlands', :abbreviation => 'NL'
    Country.create :name => 'Netherlands Antilles', :abbreviation => 'AN'
    Country.create :name => 'New Caledonia', :abbreviation => 'NC'
    Country.create :name => 'New Zealand', :abbreviation => 'NZ'
    Country.create :name => 'Nicaragua', :abbreviation => 'NI'
    Country.create :name => 'Niger', :abbreviation => 'NE'
    Country.create :name => 'Nigeria', :abbreviation => 'NG'
    Country.create :name => 'Niue', :abbreviation => 'NU'
    Country.create :name => 'Norfolk Island', :abbreviation => 'NF'
    Country.create :name => 'Northern Mariana Islands', :abbreviation => 'MP'
    Country.create :name => 'Norway', :abbreviation => 'f'
    Country.create :name => 'Oman', :abbreviation => 'OM'
    Country.create :name => 'Pakistan', :abbreviation => 'PK'
    Country.create :name => 'Palau', :abbreviation => 'PW'
    Country.create :name => 'Palestinian Territory, Occupied', :abbreviation => 'PS'
    Country.create :name => 'Panama', :abbreviation => 'PA'
    Country.create :name => 'Papua New Guinea', :abbreviation => 'PG'
    Country.create :name => 'Paraguay', :abbreviation => 'PY'
    Country.create :name => 'Peru', :abbreviation => 'PE'
    Country.create :name => 'Philippines', :abbreviation => 'PH'
    Country.create :name => 'Pitcairn', :abbreviation => 'PN'
    Country.create :name => 'Poland', :abbreviation => 'PL'
    Country.create :name => 'Portugal', :abbreviation => 'PT'
    Country.create :name => 'Puerto Rico', :abbreviation => 'PR'
    Country.create :name => 'Qatar', :abbreviation => 'QA'
    Country.create :name => 'Reunion', :abbreviation => 'RE'
    Country.create :name => 'Romania', :abbreviation => 'RO'
    Country.create :name => 'Russian Federation', :abbreviation => 'RU'
    Country.create :name => 'Rwanda', :abbreviation => 'RW'
    Country.create :name => 'Saint Helena', :abbreviation => 'SH'
    Country.create :name => 'Saint Kitts and Nevis', :abbreviation => 'KN'
    Country.create :name => 'Saint Lucia', :abbreviation => 'LC'
    Country.create :name => 'Saint Pierre and Miquelon', :abbreviation => 'PM'
    Country.create :name => 'Saint Vincent and The Grenadines', :abbreviation => 'VC'
    Country.create :name => 'Samoa', :abbreviation => 'WS'
    Country.create :name => 'San Marino', :abbreviation => 'SM'
    Country.create :name => 'Sao Tome and Principe', :abbreviation => 'ST'
    Country.create :name => 'Saudi Arabia', :abbreviation => 'SA'
    Country.create :name => 'Senegal', :abbreviation => 'SN'
    Country.create :name => 'Serbia', :abbreviation => 'RS'
    Country.create :name => 'Seychelles', :abbreviation => 'SC'
    Country.create :name => 'Sierra Leone', :abbreviation => 'SL'
    Country.create :name => 'Singapore', :abbreviation => 'SG'
    Country.create :name => 'Slovakia', :abbreviation => 'SK'
    Country.create :name => 'Slovenia', :abbreviation => 'SI'
    Country.create :name => 'Solomon Islands', :abbreviation => 'SB'
    Country.create :name => 'Somalia', :abbreviation => 'SO'
    Country.create :name => 'South Africa', :abbreviation => 'ZA'
    Country.create :name => 'South Georgia and The South Sandwich Islands', :abbreviation => 'GS'
    Country.create :name => 'Spain', :abbreviation => 'ES'
    Country.create :name => 'Sri Lanka', :abbreviation => 'LK'
    Country.create :name => 'Sudan', :abbreviation => 'SD'
    Country.create :name => 'Suriname', :abbreviation => 'SR'
    Country.create :name => 'Svalbard and Jan Mayen', :abbreviation => 'SJ'
    Country.create :name => 'Swaziland', :abbreviation => 'SZ'
    Country.create :name => 'Sweden', :abbreviation => 'SE'
    Country.create :name => 'Switzerland', :abbreviation => 'CH'
    Country.create :name => 'Syrian Arab Republic', :abbreviation => 'SY'
    Country.create :name => 'Taiwan, Province Of China', :abbreviation => 'TW'
    Country.create :name => 'Tajikistan', :abbreviation => 'TJ'
    Country.create :name => 'Tanzania, United Republic Of', :abbreviation => 'TZ'
    Country.create :name => 'Thailand', :abbreviation => 'TH'
    Country.create :name => 'Timor-leste', :abbreviation => 'TL'
    Country.create :name => 'Togo', :abbreviation => 'TG'
    Country.create :name => 'Tokelau', :abbreviation => 'TK'
    Country.create :name => 'Tonga', :abbreviation => 'TO'
    Country.create :name => 'Trinidad and Tobago', :abbreviation => 'TT'
    Country.create :name => 'Tunisia', :abbreviation => 'TN'
    Country.create :name => 'Turkey', :abbreviation => 'TR'
    Country.create :name => 'Turkmenistan', :abbreviation => 'TM'
    Country.create :name => 'Turks and Caicos Islands', :abbreviation => 'TC'
    Country.create :name => 'Tuvalu', :abbreviation => 'TV'
    Country.create :name => 'Uganda', :abbreviation => 'UG'
    Country.create :name => 'Ukraine', :abbreviation => 'UA'
    Country.create :name => 'United Arab Emirates', :abbreviation => 'AE'
    Country.create :name => 'United Kingdom', :abbreviation => 'GB'
    Country.create :name => 'United States', :abbreviation => 'US'
    Country.create :name => 'United States Minor Outlying Islands', :abbreviation => 'UM'
    Country.create :name => 'Uruguay', :abbreviation => 'UY'
    Country.create :name => 'Uzbekistan', :abbreviation => 'UZ'
    Country.create :name => 'Vanuatu', :abbreviation => 'VU'
    Country.create :name => 'Venezuela', :abbreviation => 'VE'
    Country.create :name => 'Viet Nam', :abbreviation => 'VN'
    Country.create :name => 'Virgin Islands, British', :abbreviation => 'VG'
    Country.create :name => 'Virgin Islands, U.s.', :abbreviation => 'VI'
    Country.create :name => 'Wallis and Futuna', :abbreviation => 'WF'
    Country.create :name => 'Western Sahara', :abbreviation => 'EH'
    Country.create :name => 'Yemen', :abbreviation => 'YE'
    Country.create :name => 'Zambia', :abbreviation => 'ZM'
    Country.create :name => 'Zimbabwe', :abbreviation => 'ZW'

  end

  def self.down
    drop_table :countries
  end
end
