class Morestopwords2 < ActiveRecord::Migration
  def self.up
    
    StopWord::create :word=>'shows' 
    StopWord::create :word=>'evening post'
    StopWord::create :word=>'view' 
    StopWord::create :word=>'cricket' 
    StopWord::create :word=>'looking' 
    StopWord::create :word=>'men' 
    StopWord::create :word=>'street' 
    StopWord::create :word=>'showing' 
    StopWord::create :word=>'mount victoria'
    StopWord::create :word=>'refers' 
    StopWord::create :word=>'snow' 
    StopWord::create :word=>'avian' 
    StopWord::create :word=>'location' 
    StopWord::create :word=>'tractors' 
    StopWord::create :word=>'seas' 
    StopWord::create :word=>'ships' 
    StopWord::create :word=>'societies' 
    StopWord::create :word=>'gardens' 
    StopWord::create :word=>'hills' 
    StopWord::create :word=>'mountains' 
    StopWord::create :word=>'skiing' 
    StopWord::create :word=>'trolley' 
    StopWord::create :word=>'also' 
    StopWord::create :word=>'architecture' 
    StopWord::create :word=>'automobiles' 
    StopWord::create :word=>'built' 
    StopWord::create :word=>'clouds' 
    StopWord::create :word=>'crowds' 
    StopWord::create :word=>'group' 
    StopWord::create :word=>'part' 
    StopWord::create :word=>'photo' 
    StopWord::create :word=>'sports' 
    StopWord::create :word=>'women' 
    StopWord::create :word=>'bays' 
    StopWord::create :word=>'beach' 
    StopWord::create :word=>'captain' 
    StopWord::create :word=>'dwellings' 
    StopWord::create :word=>'farms' 
    StopWord::create :word=>'general' 
    StopWord::create :word=>'great britain'
    StopWord::create :word=>'houses' 
    StopWord::create :word=>'lancaster park'
    StopWord::create :word=>'mountains' 
    StopWord::create :word=>'map' 
    StopWord::create :word=>'miramar' 
    StopWord::create :word=>'national' 
    StopWord::create :word=>'people' 
    StopWord::create :word=>'presbyterian' 
    StopWord::create :word=>'sanitoriums' 
    StopWord::create :word=>'skiers' 
    StopWord::create :word=>'swimming' 

    
  end

  def self.down
  end
end
