class Morestopwords < ActiveRecord::Migration
  def self.up
    StopWord::create :word=>'agricultural'
    StopWord::create :word=>'alcohol'
    StopWord::create :word=>'aerial'
    StopWord::create :word=>'aeroplane'
    StopWord::create :word=>'along'
    StopWord::create :word=>'also'
    StopWord::create :word=>'and'
    StopWord::create :word=>'another'
    StopWord::create :word=>'antique'
    StopWord::create :word=>'apartment'
    StopWord::create :word=>'any'
    StopWord::create :word=>'artist'
    StopWord::create :word=>'arts'
    StopWord::create :word=>'athletic'
    StopWord::create :word=>'automobiles'
    StopWord::create :word=>'avian'
    StopWord::create :word=>'babies'
    StopWord::create :word=>'bank'
    StopWord::create :word=>'bay'
    StopWord::create :word=>'bays'
    StopWord::create :word=>'beach'
    StopWord::create :word=>'bicycles'
    StopWord::create :word=>'bird'
    StopWord::create :word=>'birds'
    StopWord::create :word=>'brees'
    StopWord::create :word=>'bridges'
    StopWord::create :word=>'buildings'
    StopWord::create :word=>'bus'
    StopWord::create :word=>'buses'
    StopWord::create :word=>'business'
    StopWord::create :word=>'but'
    StopWord::create :word=>'ceo'
    StopWord::create :word=>'clouds'
    StopWord::create :word=>'cough'
    StopWord::create :word=>'cape'
    StopWord::create :word=>'captain'
    StopWord::create :word=>'car'
    StopWord::create :word=>'carriages'
    StopWord::create :word=>'christmas'
    StopWord::create :word=>'church'
    StopWord::create :word=>'cities'
    StopWord::create :word=>'colored'
    StopWord::create :word=>'commercial'
    StopWord::create :word=>'communicable'
StopWord::create :word=>'competitions'
StopWord::create :word=>'cooper'
StopWord::create :word=>'copy'
StopWord::create :word=>'cricket'
StopWord::create :word=>'crowd'
StopWord::create :word=>'crowds'
StopWord::create :word=>'cycling'
StopWord::create :word=>'cyclists'

StopWord::create :word=>'location'
StopWord::create :word=>'houses'
StopWord::create :word=>'suburbs'



  end

  def self.down
  end
end
